# plugin manager ========================================================== {{{
[[plugins]]  # プラグイン管理ツール (自分自身を管理対象にしておく)
repo = 'Shougo/dein.vim'
# }}}

# colorscheme ============================================================= {{{
[[plugins]]
repo = 'tomasr/molokai'
hook_add = 'colorscheme molokai'
# }}}

# UI ====================================================================== {{{
[[plugins]]  # status bar, tab bar のUIカスタマイズ
repo = 'itchyny/lightline.vim'
hook_add = 'execute "source " . GetNvimrcDir() . "/plugins/lightline.rc.vim"'

[[plugins]]  # インデント毎に破線を表示
repo = 'Yggdroot/indentLine'
hook_add = '''
  augroup indent_line
    autocmd!
    autocmd BufWinEnter,ShellCmdPost * IndentLinesReset
  augroup END
'''
# }}}
